services:
  - type: web
    name: brewcoffee-api
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build --filter=@repo/api...
    startCommand: pnpm --filter=@repo/database run db:migrate && pnpm --filter=@repo/api run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: brewcoffee-web
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build --filter=web...
    startCommand: pnpm --filter=web run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://brewcoffee-api.onrender.com # Change this if you rename your API service
